import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# Templates de langues
TEXTS = {
    "en": {
        "subject_prefix": "🔔 AutoNexus Alert:", "updates_for": "updates for",
        "report_title": "Surveillance Report", "intro": "Here are the latest detected updates:",
        "updated": "UPDATED", "new": "NEW", "open_link": "Open Link", "generated_by": "Generated by AutoNexus on"
    },
    "fr": {
        "subject_prefix": "🔔 Alerte AutoNexus :", "updates_for": "mises à jour pour",
        "report_title": "Rapport de Surveillance", "intro": "Voici les dernières détections :",
        "updated": "MISE À JOUR", "new": "NOUVEAU", "open_link": "Voir la source", "generated_by": "Généré par AutoNexus le"
    }
}

async def send_notification(settings: dict, items: list, credentials_str: str, lang: str = "en"):
    """
    Sends email in the requested language.
    """
    if not credentials_str or ":" not in credentials_str: return
    sender_email, app_password = credentials_str.split(":")
    recipient_email = settings.get("recipient_email") or sender_email 
    if not items: return

    # Select Language (Default to EN if unknown)
    t = TEXTS.get(lang, TEXTS["en"])

    subject = f"{t['subject_prefix']} {len(items)} {t['updates_for']} '{settings.get('query')}'"

    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <div style="background-color: #f4f4f4; padding: 20px;">
          <div style="background-color: white; padding: 20px; border-radius: 8px; max-width: 600px; margin: auto;">
            <h2 style="color: #2c3e50;">{t['report_title']}: {settings.get('query')}</h2>
            <p>{t['intro']}</p>
            <hr style="border: 0; border-top: 1px solid #eee;">
    """

    for item in items:
        status_color = "#e67e22" if item.get("is_update") else "#27ae60"
        status_text = t["updated"] if item.get("is_update") else t["new"]
        
        html_body += f"""
            <div style="margin-bottom: 15px; padding: 10px; border-left: 4px solid {status_color}; background: #fafafa;">
                <div style="font-size: 12px; font-weight: bold; color: {status_color}; margin-bottom: 5px;">{status_text}</div>
                <div style="font-size: 16px; margin-bottom: 5px;">{item['content'].replace(chr(10), '<br>')}</div>
                <a href="{item['link']}" style="display: inline-block; background: #3498db; color: white; text-decoration: none; padding: 5px 10px; border-radius: 4px; font-size: 12px;">{t['open_link']}</a>
            </div>
        """

    html_body += f"""
            <hr style="border: 0; border-top: 1px solid #eee;">
            <p style="font-size: 12px; color: #999; text-align: center;">{t['generated_by']} {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
          </div>
        </div>
      </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = subject
    msg.attach(MIMEText(html_body, 'html'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, app_password)
        text = msg.as_string()
        server.sendmail(sender_email, recipient_email, text)
        server.quit()
        print(f"[GMAIL] Sent to {recipient_email} ({lang})")
    except Exception as e:
        print(f"[GMAIL ERROR] {e}")